#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: default
  labels:
    app: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
      tier: frontend
      version: 1.0.0
#pod tempalte
  template:
    metadata:
      labels:
        app: nodejsapp
        tier: frontend
        version: 1.0.0
    spec: # Pod spec
      containers:
      - name: nodejs-container
        image: ooghenekaro/maven-demo:latest
        ports:
        - containerPort: 8080
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejsapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nodejsapp

